# Preparing for the course

In order reproduce the data management and analysis examples detailed in this book, you will need to take the following steps. 

## Download R Studio

## Create an R project

## Download the data files

We have two data sets!

### The 'Example' dataset 

This data was analysed in:

Tattersall, E. R., Burgar, J. M., Fisher, J. T., & Burton, A. C. (2020). Mammal seismic line use varies with restoration: Applying habitat restoration to species at risk conservation in a working landscape. Biological Conservation, 241, 108295.

Tattersall, E. R., Burgar, J. M., Fisher, J. T., & Burton, A. C. (2020). Boreal predator co‐occurrences reveal shared use of seismic lines in a working landscape. Ecology and Evolution, 10(3), 1678-1691.

Beirne, C., Sun, C., Tattersall, E. R., Burgar, J. M., Fisher, J. T., & Burton, A. C. (2021). Multispecies modelling reveals potential for habitat restoration to re‐establish boreal vertebrate community dynamics. Journal of Applied Ecology, 58(12), 2821-2832.

Burton, A. C., Beirne, C., Sun, C., Granados, A., Procko, M., Chen, C., ... & Burgar, J. (2022). Behavioral “bycatch” from camera trap surveys yields insights on prey responses to human‐mediated predation risk. Ecology and evolution, 12(7), e9108.

Sun, C., Burgar, J. M., Fisher, J. T., & Burton, A. C. (2022). A cautionary tale comparing spatial count and partial identity models for estimating densities of threatened and unmarked populations. Global Ecology and Conservation, 38, e02268.



### "Your" dataset 

You can either use the dataset I have provided or you can substitute these files for your own data. 

If you used the files I have provided, this is the subset of an unpublished (and as yet un analysed) dataset. I will leave it to you to find out more about it during the course!

If you want to use your own data they *MUST* be in 'Wildlife Insights' format - see the descriptions [here](https://docs.google.com/spreadsheets/d/1Jg-WybmVeGlWGrbPpwuwJCgranOV1r3M_LrzELttfK0/edit?usp=sharing) and for a existing example/template see [here](https://drive.google.com/drive/folders/1MeCeoXepyee7mADlxQZ2k0bjVBOTP5m7?usp=sharing). *NOTE* delete the description row if you are using your own data.  

The green/bolded columns shown in the template example are the **absolute minimal essential columns** - you can have more columns with other information! 


## Install the required packages

